var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};
var app={id: '_c54ec6dec86edd7b625d83aa0ccba1b9',pn: 'com.jydlui.zt',p: 0,pName: 'web',domain:"",ss:{},App:null,ipe:function(a,b){null!=app.App&&app.App.provide(a,b)},"\u63d0\u4f9b":function(a,b){null!=app.App&&app.App.provide(a,b)},zint:function(a){return parseInt(a)},zlong:function(a){return 0!=app.p?IAPP.zlong(a):parseInt(a)},zfloat:function(a){return parseFloat(a)},zdouble:function(a){return 0!=app.p?IAPP.zdouble(a):parseFloat(a)},zstring:function(a){return null===a?null:a.toString()},toColor:function(a){return 0!=app.p?IAPP.toColor(a):
a},syso:function(a){if(a instanceof Object)try{console.log(a+"="+JSON.stringify(a,null,2))}catch(b){console.log(a)}else console.log(a)},tw:function(a,b){if(void 0===b||null===b)b=2E3;if(0!=app.p)return IAPP.tw(a,b);alert(a)},sss:function(a,b,c){if(void 0===a||null===a)return null;a=a.replace(/\/|\\|:|\*|\?|<|>|\|/g,"");if(void 0===b||null===b||"g"===b)return window.localStorage.getItem(a);if("s"===b)window.localStorage.setItem(a,c);else if("d"===b)window.localStorage.removeItem(a);else if("l"===b){a=
[];c=window.localStorage.length;for(var e=0,d=0;d<c;d++)b=window.localStorage.key(d),null==b||-1!=b.indexOf("/")&&-1!=b.indexOf("\\")||(a[e]=b,e++);return a}return null},fd:function(a){return 0!=app.p?IAPP.fd(a):null!=window.localStorage.getItem(a)?(window.localStorage.removeItem(a),!0):!1},fe:function(a){return 0!=app.p?IAPP.fe(a):null!=window.localStorage.getItem(a)},fs:function(a){if(0!=app.p)return IAPP.fs(a);a=window.localStorage.getItem(a);return null!=a?a.length:-1},fr:function(a,b){if(void 0===
b||null===b)b="utf-8";return 0!=app.p?IAPP.fr(a,b):window.localStorage.getItem(a)},fc:function(a,b,c){if(void 0===c||null===c)c=!0;if(0!=app.p)return IAPP.fc(a,b,c);a=window.localStorage.getItem(a);if(null!=a){if(!c&&null!=window.localStorage.getItem(b))return!1;window.localStorage.setItem(b,a);return!0}return!1},fw:function(a,b,c){if(void 0===c||null===c)c="utf-8";if(0!=app.p)return IAPP.fw(a,b,c);window.localStorage.setItem(a,b)},fl:function(a,b){if(0!=app.p)return a=void 0!=b?IAPP.fl(a,b):IAPP.fl(a),
1===app.p?null===a||void 0===a?a:JSON.parse(a):a;a=a.replace(/\\/g,"/");a.endsWith("/")||(a+="/");for(var c,e,d=[],f=window.localStorage.length,g=0,k=a.length,h,l=0;l<f;l++)c=window.localStorage.key(l),null!=c&&(e=c.replace(/\\/g,"/"),0==a.indexOf(e)&&(e=e.substring(k),void 0===b?(h=e.indexOf("/"),-1==h?(d[g]=c,g++):(c=e.substring(0,h),-1==d.indexOf(c)&&(d[g]=c,g++))):!0===b?(h=e.indexOf("/"),-1!=h&&(c=e.substring(0,h),-1==d.indexOf(c)&&(d[g]=c,g++))):!1===b&&(h=e.indexOf("/"),-1==h&&(d[g]=c,g++))))},
ft:function(a,b,c){if(void 0===c||null===c)c=!0;if(0!=app.p)return IAPP.ft(a,b,c);var e=window.localStorage.getItem(a);if(null!=e){if(!c&&null!=window.localStorage.getItem(b))return!1;window.localStorage.setItem(b,e);window.localStorage.removeItem(a);return!0}return!1},fdir:function(a){return 0!=app.p?void 0!=a?IAPP.fdir(a):IAPP.fdir():void 0===a||null===a?"":a},fuz:function(a,b,c,e){if(void 0===e||null===e)e=!0;return 0!=app.p?IAPP.fuz(a,b,c,e):-1},fuzs:function(a,b,c){if(void 0===c||null===c)c=
!0;return 0!=app.p?IAPP.fuzs(a,b,c):-1},fo:function(a){if(0!=app.p)return IAPP.fo(a);window.location.href=fo},fj:function(a,b,c){if(void 0===c||null===c)c=!0;return 0!=app.p?IAPP.fj(a,b,c):-1},ff:function(a,b){if(0!=app.p)return void 0===b&&(b=null),a=IAPP.ff(a,b),1===app.p?null===a||void 0===a?a:JSON.parse(a):a;a=a.replace(/\\/g,"/");a.endsWith("/")||(a+="/");for(var c,e=window.localStorage.length,d=0,f=a.length,g,k=0;k<e;k++)if(c=window.localStorage.key(k),null!=c&&(c=window.localStorage.getItem(c),
null!=c&&(c=c.replace(/\\/g,"/"),0==a.indexOf(c))))if(null==b)d++;else{c=c.substring(f);g=c.lastIndexOf("/");-1!=g&&(c=c.substring(g+1));g=$jscomp.makeIterator(b);for(var h=g.next();!h.done;h=g.next())h=h.value,h.startsWith("*")?c.endsWith(h.substring(1))&&d++:h.endsWith("*")?c.startsWith(h.substring(0,h.length-1))&&d++:-1!=c.indexOf(h)&&d++}},fi:function(a){if(0!=app.p)return IAPP.fi(a);a=a.replace(/\\/g,"/");a.endsWith("/")||(a+="/");for(var b,c=window.localStorage.length,e=0;e<c;e++)if(b=window.localStorage.key(e),
null!=b&&(b=window.localStorage.getItem(b),null!=b&&(b=b.replace(/\\/g,"/"),0==b.indexOf(a))))return!0;return!1},ftype:function(a){if(0!=app.p)return IAPP.ftype(a);var b=a=a.replace(/\\/g,"/");b.endsWith("/")||(b+="/");for(var c,e=window.localStorage.length,d=0;d<e;d++)if(c=window.localStorage.key(d),null!=c&&(c=window.localStorage.getItem(c),null!=c)){c=c.replace(/\\/g,"/");if(a==c)return 1;if(0==c.indexOf(b))return 2}return-1},s2:function(a){return a.toFixed(2)},sn:function(a){return a},sr:function(a,
b,c,e){if(void 0===e||null===e)e=!1;return e||"undefined"===typeof String.prototype.replaceAll?a.replace(b,c):a.replaceAll(b,c)},sj:function(a,b,c){var e=0;if(null!=b){e=a.indexOf(b);if(-1==e)return null;e+=b.length}if(null==c)b=a.length;else if(b=a.indexOf(c,e),-1==b)return null;return a.substring(e,b)},sl:function(a,b,c){return a.split(b)},siof:function(a,b,c){return void 0===c||null===c?a.indexOf(b):a.indexOf(b,c)},slof:function(a,b,c){return void 0===c||null===c?a.lastIndexOf(b):a.lastIndexOf(b,
c)},ssg:function(a,b,c){return void 0===c||null===c?a.substring(b):a.substring(b,c)},slg:function(a){return null===a||void 0===a?0:a.toString().length},strim:function(a){return null===a||void 0===a?null:a.toString().trim()},slower:function(a){return null===a||void 0===a?null:a.toString().toLowerCase()},supper:function(a){return null===a||void 0===a?null:a.toString().toUpperCase()},sran:function(a,b){a=Math.ceil(a);return Math.floor(Math.random()*(Math.floor(b)-a+1))+a},hs:function(a,b,c,e){return 0==
app.p||void 0===b&&void 0===c&&void 0===e?null:void 0===c&&void 0===e?IAPP.hs(a,b):void 0===e?IAPP.hs(a,b,c):IAPP.hs(a,b,c,e)},hd:function(a,b,c,e,d,f){if(0!=app.p)return void 0===c&&void 0===e&&void 0===d&&void 0===f?IAPP.hd(a,b):void 0===e&&void 0===d&&void 0===f?IAPP.hd(a,b,c):IAPP.hd(a,b,c,e,d,f);window.location.href=a;return null},hw:function(a){0!=app.p?IAPP.hw(a):null==window.open(a,"newWindow","width=800,height=600")&&(window.location.href=a)},sxb:function(a){0!=app.p?IAPP.sxb(a):navigator.clipboard.writeText(a)},
shb:function(){return 0!=app.p?IAPP.shb():navigator.clipboard.readText()},end:function(){0!=app.p?IAPP.end():window.close()},ends:function(){0!=app.p&&IAPP.ends()},time:function(a){if(0!=app.p)return IAPP.time(a);if(Number.isInteger(a))return 0==a?(new Date).toLocaleString().replace(/\//g,"-"):1==a?(new Date).toLocaleString():2==a?(new Date).toLocaleDateString():3==a?(new Date).toLocaleTimeString():4==a?(new Date).getTime().toString():6==a?(new Date).toLocaleString().replace("/","\u5e74").replace("/",
"\u6708").replace(" ","\u65e5 ").replace(":","\u65f6").replace(":","\u5206")+"\u79d2":(new Date).toLocaleString().replace("/","\u5e74").replace("/","\u6708").replace(" ","\u65e5 ");a=a.toString();if("y"==a||"Y"==a)return(new Date).getFullYear();if("m"===a)return(new Date).getMonth();if("d"===a)return(new Date).getDate();if("h"===a||"H"===a)return(new Date).getHours();if("M"===a)return(new Date).getMinutes();if("S"===a||"s"===a)return(new Date).getSeconds();if("a"===a||"A"===a)return(new Date).getDay()},
huf:function(a,b,c,e,d){return 0!=app.p?IAPP.huf(a,b,c,e,d):null},androidKeyDown:null,androidKeyDownX:function(a,b){null!=app.androidKeyDown&&app.androidKeyDown(a,b)},androidKeyUp:null,androidKeyUpX:function(a,b){null!=app.androidKeyUp&&app.androidKeyUp(a,b)},androidResume:null,androidResumeX:function(){null!=app.androidResume&&app.androidResume()},androidPause:null,androidPauseX:function(){null!=app.androidPause&&app.androidPause()},androidStop:null,androidStopX:function(){null!=app.androidStop&&
app.androidStop()},androidRestart:null,androidRestartX:function(){null!=app.androidRestart&&app.androidRestart()},androidDestroy:null,androidDestroyX:function(){null!=app.androidDestroy&&app.androidDestroy()},androidRequestPermissionsResult:null,androidRequestPermissionsResultX:function(a,b,c){null!=app.androidRequestPermissionsResult&&app.androidRequestPermissionsResult(a,b,c)},androidActivityResult:null,androidActivityResultX:function(a,b,c){null!=app.androidActivityResult&&app.androidActivityResult(a,
b,c)}};function syso(a){app.syso(a)}function sysoerr(a){console.error("\u9519\u8bef: "+a)}
function hs(a,b,c,e){if("ios"==app.pName||"mac"==app.pName){var d=a.toLowerCase();if(d.startsWith("http:")||d.startsWith("https:"))if(10>app.domain.length||!a.startsWith(app.domain))a="i"+a}d=arguments.length;var f=new XMLHttpRequest;if(2===d)f.open("get",a,!0),f.send(null),f.onreadystatechange=function(){f.readyState===XMLHttpRequest.DONE&&b instanceof Function&&(200===f.status?b(f.responseText,null,f):b(null,f.statusText,f))};else if(3===d)f.open("post",a,!0),d=b.toString().trim().charAt(0),"{"===
d||"["===d?f.setRequestHeader("Content-Type","application/json; charset-utf-8"):f.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset-utf-8"),f.send(b),f.onreadystatechange=function(){f.readyState===XMLHttpRequest.DONE&&c instanceof Function&&(200===f.status?c(f.responseText,null,f):c(null,f.statusText,f))};else{if(null===b||void 0===b)f.open("get",a,!0),f.send(null);else{if(null===c||void 0===c)c="utf-8";f.open("post",a,!0);d=b.toString().trim().charAt(0);"{"===d||"["===d?
f.setRequestHeader("Content-Type","application/json; charset-"+c):f.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset-"+c);f.send(b)}f.onreadystatechange=function(){f.readyState===XMLHttpRequest.DONE&&e instanceof Function&&(200===f.status?e(f.responseText,null,f):e(null,f.statusText,f))}}}
function huf(a,b,c,e){if("ios"==app.pName||"mac"==app.pName){var d=a.toLowerCase();if(d.startsWith("http:")||d.startsWith("https:"))if(10>app.domain.length||!a.startsWith(app.domain))a="i"+a}var f=new XMLHttpRequest;f.open("post",a,!0);a=new FormData;if(null!=b)if(Array.isArray(b)){b=$jscomp.makeIterator(b);for(var g=b.next();!g.done;g=b.next())g=g.value,"string"===typeof g?(d=g.indexOf("="),a.append(g.substring(0,d),g.substring(d+1))):a.append(g.name,g.value)}else"string"===typeof b?(d=b.indexOf("="),
a.append(b.substring(0,d),b.substring(d+1))):a.append(b.name,b.value);if(Array.isArray(c))for(d=$jscomp.makeIterator(c),g=d.next();!g.done;g=d.next())if(b=g.value,"string"===typeof b){g=document.getElementById(b);var k=$jscomp.makeIterator(g.files);for(b=k.next();!b.done;b=k.next())a.append(g.name,b.value)}else for(g=$jscomp.makeIterator(c.files),b=g.next();!b.done;b=g.next())a.append(c.name,b.value);else if("string"===typeof c)for(c=document.getElementById(c),d=$jscomp.makeIterator(c.files),b=d.next();!b.done;b=
d.next())a.append(c.name,b.value);else for(d=$jscomp.makeIterator(c.files),b=d.next();!b.done;b=d.next())a.append(c.name,b.value);f.onload=function(){e instanceof Function&&(200===f.status?e(f.responseText,null,f):e(null,f.statusText,f))};f.send(a)}function tsi(a,b){return null===b||void 0===b?(window.clearInterval(a),null):window.setInterval(b,a)}function tst(a,b){return null===b||void 0===b?(window.clearTimeout(a),null):window.setTimeout(b,a)}function dgei(a){return document.getElementById(a)}
function dgecn(a){return document.getElementsByClassName(a)}function dgetn(a){return document.getElementsByTagName(a)}function dgen(a){return document.getElementsByName(a)}
function dce(a){var b=arguments.length;if(1==b)return document.createElement(a);if(1<b){var c=document.createElement(a);if(2==b&&arguments[1]instanceof Array){b=arguments[1];for(var e=b.length,d=0;d<e;d++)0==b[d].indexOf("text=")?c.textContent=b[d].substring(5):(i2=b[d].indexOf("="),-1!=i2&&c.setAttribute(b[d].substring(0,i2),b[d].substring(i2+1)))}else if(2==b&&arguments[1]instanceof Object){b=arguments[1];e=Object.keys(b);d=e.length;for(var f=0;f<d;f++)"text"===e[f]?c.textContent=b[e[f]]:c.setAttribute(e[f],
b[e[f]])}else for(d=1;d<b;d++)0==arguments[d].indexOf("text=")?c.textContent=arguments[d].substring(5):(e=arguments[d].indexOf("="),-1!=e&&c.setAttribute(arguments[d].substring(0,e),arguments[d].substring(e+1)));return c}return null}function dac(a,b){a instanceof HTMLElement||(a=document.getElementById(a));return a.appendChild(b)}
function drc(a,b){a instanceof HTMLElement||(a=document.getElementById(a));if(void 0===b||null===b){b=a.parentNode;if(null===b)return!1;b.removeChild(a);return!b.contains(a)}if(b instanceof HTMLElement)return a.removeChild(b),!a.contains(b);for(var c=null,e=$jscomp.makeIterator(a.children),d=e.next();!d.done;d=e.next())d=d.value,d.id===b&&(c=d,a.removeChild(c));return null!=c}function dcn(a){return a instanceof HTMLElement?a.children:document.getElementById(a).children}
function dcnct(a){return a instanceof HTMLElement?a.childElementCount:document.getElementById(a).childElementCount}function isnull(a){return null===a||void 0===a}var sss=window,\u6211\u5e94\u7528=app,\u662f=!0,\u5426=!1,\u7a7a=void 0;function \u8f93\u51fa(a){app.syso(a)}function \u8f93\u51fa\u9519\u8bef(a){console.error("\u9519\u8bef: "+a)}function \u7f51\u7edc\u83b7\u53d6(a,b,c,e){hs(a,b,c,e)}function \u6587\u4ef6\u4e0a\u4f20(a,b,c,e,d){huf(a,b,c,e,d)}
function \u5b9a\u65f6\u5668\u95f4\u9694(a,b){return tsi(a,b)}function \u5b9a\u65f6\u5668\u5ef6\u8fdf(a,b){return tst(a,b)}function \u83b7\u53d6\u7f16\u53f7\u5143\u7d20(a){return document.getElementById(a)}function \u83b7\u53d6\u7c7b\u540d\u5143\u7d20(a){return document.getElementsByClassName(a)}function \u83b7\u53d6\u6807\u7b7e\u5143\u7d20(a){return dgetn(a)}function \u83b7\u53d6\u540d\u79f0\u5143\u7d20(a){return dgen(a)}
function \u5143\u7d20\u521b\u5efa(a){var b=arguments.length;if(1==b)return document.createElement(a);if(1<b){var c=document.createElement(a);if(2==b&&arguments[1]instanceof Array){b=arguments[1];for(var e=b.length,d=0;d<e;d++)0==b[d].indexOf("text=")?c.textContent=b[d].substring(5):(i2=b[d].indexOf("="),-1!=i2&&c.setAttribute(b[d].substring(0,i2),b[d].substring(i2+1)))}else if(2==b&&arguments[1]instanceof Object){b=arguments[1];e=Object.keys(b);d=e.length;for(var f=0;f<d;f++)"text"===e[f]?c.textContent=
b[e[f]]:c.setAttribute(e[f],b[e[f]])}else for(d=1;d<b;d++)0==arguments[d].indexOf("text=")?c.textContent=arguments[d].substring(5):(e=arguments[d].indexOf("="),-1!=e&&c.setAttribute(arguments[d].substring(0,e),arguments[d].substring(e+1)));return c}return null}function \u5143\u7d20\u6dfb\u52a0(a,b){return dac(a,b)}function \u5143\u7d20\u5220\u9664(a,b){return drc(a,b)}function \u5b50\u5143\u7d20(a){return dcn(a)}function \u5b50\u5143\u7d20\u6570\u91cf(a){return dcnct(a)}
function \u662f\u5426\u4e3a\u7a7a(a){return isnull(a)};